#!/usr/bin/env ruby
require_relative '../lib/docker_kit.rb'

# https://docs.docker.com/engine/reference/builder/#arg
# http_proxy可以不指定ARG http_proxy指令，但要指定--build-arg 和外部环境变量, 内置支持，参见官方文档
$dockerfile = <<~Desc
  FROM alpine
  ARG var_in_args
  #ARG var_not_in_args
  ARG var_missing
  RUN echo =========== && \
      echo http_proxy=$http_proxy && \
      echo var_in_args=$var_in_args
     
  CMD sh -c 'echo ==inspect vars: \
        var_in_args=$var_in_args \
        var_not_in_args=$var_not_in_args \
        var_missing=$var_missing \
        http_proxy=$http_proxy \
        path=$PATH'
Desc

class DockletCLI < DockletBase

  def main
    super
    puts "==run with docker build args"
    system <<~Desc
      docker run --rm --env var_not_in_args=b1 #{dock_image}
      docker run --rm --env name=test #{dock_image} env
    Desc
  end

  def build
    file = Tempfile.new('docklet')
    begin
      file.write $dockerfile
      file.close # save to disk
      #system "docker build --file #{file.path} --tag #{dock_image} ."
      #donot need build context
      system <<~Script
        export var_in_args='a1'
        export var_missing='c1'
        export http_proxy='http_proxy1'
        cat #{file.path} | docker build --force-rm --rm --build-arg var_in_args=a0 --build-arg http_proxy --tag #{dock_image} -
      Script
    ensure
      file.unlink
    end
  end
end

DockletCLI.start
