#!/usr/bin/env ruby
require_relative '../lib/docker_kit.rb'

set_dockerfile <<~Desc
  FROM ubuntu:16.04
  MAINTAINER Cao Ruijian <cao7113@hotmail.com>

  RUN apt-get -y update 
  RUN apt-get install -y openssh-server && \
      mkdir /var/run/sshd && \
      echo 'root:root' | chpasswd && \
      sed -ri 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
      sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

  ## SSH login fix. Otherwise user is kicked off after login
  #RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
  #ENV NOTVISIBLE "in users profile"
  #RUN echo "export VISIBLE=now" >> /etc/profile

  EXPOSE 22
  CMD ["/usr/sbin/sshd", "-D"]
Desc

let_cli_magic_start!
