#!/usr/bin/env ruby
require_relative '../lib/docker_kit.rb'

$dockerfile = <<~Desc
  FROM alpine
  ENV name=geek
  ENV name1=${name}-1
  CMD sh -c 'echo name=$name name1=$name1'
Desc

class DockletCLI < DockletBase
  def user_main
    # 构建时指定的环境变量在运行时可以覆盖, 但已被引用的不会动态evaluate
    puts "==runtime env"
    system "docker run --rm #{dock_image}"
    puts "==runtime env with host env set"
    system "env name=test docker run --rm #{dock_image}"
    puts "==runtime env with docker env set"
    system "docker run --rm --env name=test #{dock_image}"
  end
end

DockletCLI.start
