FROM ruby:2.5-alpine3.7
LABEL <%=image_labels%>
RUN apk add build-base sqlite-dev &&       gem install --no-ri --no-rdoc gemstash
EXPOSE 9292
VOLUME /root/.gemstash
ENTRYPOINT ["gemstash"]
CMD ["start", "--no-daemonize"]
