#!/usr/bin/env ruby
require_relative '../lib/docker_kit.rb'

set_dockerfile <<~Desc
  FROM ruby:2-alpine3.7
  WORKDIR /app
  COPY try.rb /app
  CMD /app/try.rb
Desc

set_file_for :jobspec, <<~Desc
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: hijob
  spec:
    # retry times before fail
    backoffLimit: 3
    # wait job running time in seconds
    activeDeadlineSeconds: 600
    template:
      spec:
        containers:
        - name: hijob
          image: <%=docker_image%>
        restartPolicy: Never
Desc

class DockletCLI < DockletBase
  def main
    invoke_clean
    super
    system <<~Desc
      kubectl create -f #{jobfile} 
      sleep 3
      kubectl logs job/hijob
    Desc
  end

  desc 'clean', ''
  def clean
    system 'kubectl delete job/hijob'
    super
  end

  def build
    system <<~Desc
      docker build --tag #{docker_image} --file #{dockerfile} #{script_path}
    Desc
  end

  desc 'jobspec', ''
  def jobspec
    puts File.read(jobfile)
  end

  no_commands do
    def jobfile
      @_jobfile ||= rendered_file_for(:jobspec)
    end
  end
end

DockletCLI.start
